Section "InputClass"
    Identifier      "iiyama touch evdev"
    MatchProduct    "Melfas LGDisplay Incell Touch"
    MatchDevicePath "/dev/input/event*"
    MatchIsTouchscreen "on"
    Driver          "evdev"
EndSection
