export const ALL_PERMISSIONS = [
  'view_calendar',
  'add_calendar_event',
  'edit_calendar_event',
  'delete_calendar_event',
  'view_food',
  'add_recipe',
  'add_to_shopping',
  'tick_shopping',
  'clear_shopping',
  'view_vehicles',
  'book_vehicle',
  'manage_vehicles',
  'view_chores',
  'complete_chore',
  'manage_chores',
  'view_health_log',
  'add_health_log',
  'view_finance',
  'manage_finance',
  'view_house',
  'manage_house',
  'view_pets',
  'manage_pets',
  'view_board',
  'post_board_message',
  'view_contacts',
  'manage_contacts',
  'manage_settings',
  'manage_plugins',
] as const;

export type PermissionKey = (typeof ALL_PERMISSIONS)[number];
